/* Offline level generation. Usage: npm run levels:generate */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { levelCanonicalKey } from '../src/game/canonical';
import { LEVEL_SPECS } from '../src/game/difficulty';
import { generateLevel, GENERATOR_VERSION } from '../src/game/generator';
import { tubeToString } from '../src/game/levelCodec';
import { HANDCRAFTED_LEVELS } from '../src/data/levels.handcrafted';

const seen = new Set<string>(HANDCRAFTED_LEVELS.map((l) => levelCanonicalKey(l)));
const blocks: string[] = [];

for (const spec of LEVEL_SPECS) {
  const seed = `level-${spec.number}`;
  const res = generateLevel(spec, seed, { seen });
  if (!res) throw new Error(`Could not generate level ${spec.number} (window ${spec.optMin}-${spec.optMax})`);
  const { level: l, metrics: m, attempts } = res;
  console.log(`${l.id} ${l.difficulty.padEnd(6)} colours=${spec.colors.length} optimal=${m.optimal} branching=${m.branching} deadEnd=${m.deadEndRate.toFixed(2)} attempts=${attempts}`);
  blocks.push(
    `  // optimal=${m.optimal} branching=${m.branching} deadEndRate=${m.deadEndRate.toFixed(2)} attempts=${attempts}\n` +
    `  defineLevel({\n` +
    `    id: '${l.id}', number: ${l.number}, chapter: ${l.chapter}, difficulty: '${l.difficulty}',\n` +
    `    optimalMoves: ${l.optimalMoves}, optimalIsExact: ${l.optimalIsExact},\n` +
    `    tubes: [${l.tubes.map((t) => `'${tubeToString(t)}'`).join(', ')}],\n` +
    `    meta: { generatorVersion: '${l.meta.generatorVersion}', seed: '${l.meta.seed}' },\n` +
    `  }),`,
  );
}

const out =
  `// GENERATED by scripts/generate-levels.ts (generator ${GENERATOR_VERSION}). Do not edit by hand.\n` +
  `// Tubes are written bottom -> top; '' is an empty tube.\n` +
  `import { defineLevel } from '../game/levelCodec';\n` +
  `import type { Level } from '../game/types';\n\n` +
  `export const GENERATED_LEVELS: Level[] = [\n${blocks.join('\n')}\n];\n`;
writeFileSync(join(__dirname, '../src/data/levels.generated.ts'), out);
console.log(`Wrote ${blocks.length} levels`);
