/* Offline level generation. Usage: npm run levels:generate */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { levelCanonicalKey } from '../src/game/canonical';
import { LEVEL_SPECS, MECH_SPECS, MIX_SPECS } from '../src/game/difficulty';
import { generateLevel, GENERATOR_VERSION } from '../src/game/generator';
import { toCompactTube, tubeToString } from '../src/game/levelCodec';
import { HANDCRAFTED_LEVELS } from '../src/data/levels.handcrafted';
import { generateMechLevel } from '../src/game/mechGenerator';
import { generateMixLevel } from '../src/game/mixGenerator';

const seen = new Set<string>(HANDCRAFTED_LEVELS.map((l) => levelCanonicalKey(l)));
const blocks: string[] = [];

for (const spec of LEVEL_SPECS) {
  const seed = `level-${spec.number}`;
  const res = generateLevel(spec, seed, { seen });
  if (!res) throw new Error(`Could not generate level ${spec.number} (window ${spec.optMin}-${spec.optMax})`);
  const { level: l, metrics: m, attempts } = res;
  console.log(`${l.id} ${l.difficulty.padEnd(6)} colours=${spec.colors.length} optimal=${m.optimal} branching=${m.branching} deadEnd=${m.deadEndRate.toFixed(2)} attempts=${attempts}`);
  blocks.push(
    `  // optimal=${m.optimal} branching=${m.branching} deadEndRate=${m.deadEndRate.toFixed(2)} attempts=${attempts}\n` +
    `  defineLevel({\n` +
    `    id: '${l.id}', number: ${l.number}, chapter: ${l.chapter}, difficulty: '${l.difficulty}',\n` +
    `    optimalMoves: ${l.optimalMoves}, optimalIsExact: ${l.optimalIsExact},\n` +
    `    tubes: [${l.tubes.map((t) => `'${tubeToString(t)}'`).join(', ')}],\n` +
    `    meta: { generatorVersion: '${l.meta.generatorVersion}', seed: '${l.meta.seed}' },\n` +
    `  }),`,
  );
}

const out =
  `// GENERATED by scripts/generate-levels.ts (generator ${GENERATOR_VERSION}). Do not edit by hand.\n` +
  `// Tubes are written bottom -> top; '' is an empty tube.\n` +
  `import { defineLevel } from '../game/levelCodec';\n` +
  `import type { Level } from '../game/types';\n\n` +
  `export const GENERATED_LEVELS: Level[] = [\n${blocks.join('\n')}\n];\n`;
writeFileSync(join(__dirname, '../src/data/levels.generated.ts'), out);
console.log(`Wrote ${blocks.length} levels`);

// --- chapters 3-5 ---------------------------------------------------------------
const mechBlocks: string[] = [];
for (const spec of MECH_SPECS) {
  const seed = `level-${spec.number}`;
  const res = generateMechLevel(spec, seed, { seen, maxAttempts: 6000 });
  if (!res) throw new Error(`Could not generate level ${spec.number} (window ${spec.optMin}-${spec.optMax})`);
  const l = res.level;
  console.log(`${l.id} ch${l.chapter} ${l.difficulty.padEnd(6)} optimal=${l.optimalMoves} classic=${res.classicOptimal} attempts=${res.attempts}${l.rules?.reactor ? ' reactor' : ''}`);
  mechBlocks.push(
    `  // optimal=${l.optimalMoves} (same deal without the mechanic: ${res.classicOptimal}) attempts=${res.attempts}\n` +
    `  defineLevel({\n` +
    `    id: '${l.id}', number: ${l.number}, chapter: ${l.chapter}, difficulty: '${l.difficulty}',\n` +
    `    optimalMoves: ${l.optimalMoves}, optimalIsExact: ${l.optimalIsExact},\n` +
    `    tubes: [\n${l.tubes.map((t) => `      ${JSON.stringify(toCompactTube(t))},`).join('\n')}\n    ],\n` +
    (l.rules ? `    rules: ${JSON.stringify(l.rules)},\n` : '') +
    `    meta: { generatorVersion: '${l.meta.generatorVersion}', seed: '${l.meta.seed}' },\n` +
    `  }),`,
  );
}
writeFileSync(
  join(__dirname, '../src/data/levels.mechanics.generated.ts'),
  `// GENERATED by scripts/generate-levels.ts (generator ${GENERATOR_VERSION}). Do not edit by hand.\n` +
    `// Chapters 3-5 (section 11): frozen liquid, mystery liquid, catalysts and locked tubes.\n` +
    `// Tube rows are bottom -> top; '^' marks a frozen layer and '?' a hidden one.\n` +
    `import { defineLevel } from '../game/levelCodec';\n` +
    `import type { Level } from '../game/types';\n\n` +
    `export const MECHANIC_LEVELS: Level[] = [\n${mechBlocks.join('\n')}\n];\n`,
);
console.log(`Wrote ${mechBlocks.length} mechanic levels`);

// --- chapter 6 ------------------------------------------------------------------
const mixBlocks: string[] = [];
for (const spec of MIX_SPECS) {
  const seed = `level-${spec.number}`;
  const res = generateMixLevel(spec, seed, { seen, maxAttempts: 6000 });
  if (!res) throw new Error(`Could not generate level ${spec.number} (window ${spec.optMin}-${spec.optMax})`);
  const l = res.level;
  console.log(`${l.id} ch${l.chapter} ${l.difficulty.padEnd(6)} optimal=${l.optimalMoves} mixes=${res.mixes} attempts=${res.attempts}${l.rules?.reactor ? ' reactor' : ''}`);
  mixBlocks.push(
    `  // optimal=${l.optimalMoves} (${res.mixes} mixing pours) attempts=${res.attempts}\n` +
    `  defineLevel({\n` +
    `    id: '${l.id}', number: ${l.number}, chapter: ${l.chapter}, difficulty: '${l.difficulty}',\n` +
    `    optimalMoves: ${l.optimalMoves}, optimalIsExact: ${l.optimalIsExact},\n` +
    (l.tutorial ? `    tutorial: '${l.tutorial}',\n` : '') +
    `    tubes: [\n${l.tubes.map((t) => `      ${JSON.stringify(toCompactTube(t))},`).join('\n')}\n    ],\n` +
    `    rules: ${JSON.stringify(l.rules)},\n` +
    `    meta: { generatorVersion: '${l.meta.generatorVersion}', seed: '${l.meta.seed}' },\n` +
    `  }),`,
  );
}
writeFileSync(
  join(__dirname, '../src/data/levels.mixing.generated.ts'),
  `// GENERATED by scripts/generate-levels.ts (generator ${GENERATOR_VERSION}). Do not edit by hand.\n` +
    `// Chapters 6-7 (section 11.6): colour mixing, alone and with the other mechanics. Every level is unsolvable without mixing.\n` +
    `import { defineLevel } from '../game/levelCodec';\n` +
    `import type { Level } from '../game/types';\n\n` +
    `export const MIXING_LEVELS: Level[] = [\n${mixBlocks.join('\n')}\n];\n`,
);
console.log(`Wrote ${mixBlocks.length} mixing levels`);
