/* Generates the 60 pre-verified fallback daily puzzles. Usage: npx tsx scripts/generate-daily-pool.ts */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { DAILY_POOL_SIZE } from '../src/game/daily';
import { generateLevel, GENERATOR_VERSION } from '../src/game/generator';
import type { LevelSpec } from '../src/game/generator';
import { tubeToString } from '../src/game/levelCodec';
import type { LiquidColor } from '../src/game/types';

const COLORS: LiquidColor[] = ['red', 'blue', 'green', 'yellow', 'purple', 'orange'];
const seen = new Set<string>();
const rows: string[] = [];

for (let i = 0; i < DAILY_POOL_SIZE; i++) {
  const six = i % 2 === 1;
  const spec: LevelSpec = {
    number: 0, chapter: 0, difficulty: six ? 'hard' : 'medium',
    colors: COLORS.slice(0, six ? 6 : 5), empties: 2, optMin: six ? 17 : 14, optMax: six ? 21 : 18,
  };
  const seed = `daily-pool-${i}`;
  const res = generateLevel(spec, seed, { seen });
  if (!res || !res.level.optimalIsExact) throw new Error(`pool entry ${i} failed`);
  const { level } = res;
  rows.push(`  { seed: '${seed}', difficulty: '${spec.difficulty}', optimalMoves: ${level.optimalMoves}, tubes: [${level.tubes.map((t) => `'${tubeToString(t)}'`).join(', ')}] },`);
  console.log(i, spec.difficulty, level.optimalMoves);
}

writeFileSync(
  join(__dirname, '../src/data/daily.pool.ts'),
  `// GENERATED by scripts/generate-daily-pool.ts (generator ${GENERATOR_VERSION}). Do not edit by hand.\n` +
    `// Fallback daily puzzles, indexed by date hash when on-device generation fails (§12.4).\n` +
    `import type { PoolEntry } from '../game/daily';\n\nexport const DAILY_POOL: PoolEntry[] = [\n${rows.join('\n')}\n];\n`,
);
