// GENERATED by scripts/generate-levels.ts (generator g1). Do not edit by hand.
// Tubes are written bottom -> top; '' is an empty tube.
import { defineLevel } from '../game/levelCodec';
import type { Level } from '../game/types';

export const GENERATED_LEVELS: Level[] = [
  // optimal=6 branching=6 deadEndRate=0.00 attempts=6
  defineLevel({
    id: 'L002', number: 2, chapter: 1, difficulty: 'easy',
    optimalMoves: 6, optimalIsExact: true,
    tubes: ['BBRR', 'GGBG', 'RRGB', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-2' },
  }),
  // optimal=6 branching=6 deadEndRate=0.00 attempts=3
  defineLevel({
    id: 'L003', number: 3, chapter: 1, difficulty: 'easy',
    optimalMoves: 6, optimalIsExact: true,
    tubes: ['BBRG', 'GRBB', 'RRGG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-3' },
  }),
  // optimal=7 branching=6 deadEndRate=0.00 attempts=6
  defineLevel({
    id: 'L004', number: 4, chapter: 1, difficulty: 'easy',
    optimalMoves: 7, optimalIsExact: true,
    tubes: ['BRBB', 'RRGR', 'GBGG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-4' },
  }),
  // optimal=8 branching=6 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L005', number: 5, chapter: 1, difficulty: 'easy',
    optimalMoves: 8, optimalIsExact: true,
    tubes: ['RRBR', 'BGBG', 'GGRB', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-5' },
  }),
  // optimal=9 branching=8 deadEndRate=0.00 attempts=53
  defineLevel({
    id: 'L006', number: 6, chapter: 1, difficulty: 'easy',
    optimalMoves: 9, optimalIsExact: true,
    tubes: ['GGGY', 'RBRB', 'YRRB', 'GYYB', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-6' },
  }),
  // optimal=10 branching=8 deadEndRate=0.00 attempts=2
  defineLevel({
    id: 'L007', number: 7, chapter: 1, difficulty: 'easy',
    optimalMoves: 10, optimalIsExact: true,
    tubes: ['YRBY', 'RRGG', 'YYBR', 'BGBG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-7' },
  }),
  // optimal=11 branching=8 deadEndRate=0.00 attempts=4
  defineLevel({
    id: 'L008', number: 8, chapter: 1, difficulty: 'easy',
    optimalMoves: 11, optimalIsExact: true,
    tubes: ['GYRR', 'BBYY', 'BYGB', 'GRGR', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-8' },
  }),
  // optimal=12 branching=8 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L009', number: 9, chapter: 1, difficulty: 'medium',
    optimalMoves: 12, optimalIsExact: true,
    tubes: ['GRGR', 'RBYB', 'GRBY', 'YYBG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-9' },
  }),
  // optimal=13 branching=8 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L010', number: 10, chapter: 1, difficulty: 'medium',
    optimalMoves: 13, optimalIsExact: true,
    tubes: ['YBYB', 'YRGG', 'YRGR', 'BGBR', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-10' },
  }),
  // optimal=13 branching=10 deadEndRate=0.00 attempts=3
  defineLevel({
    id: 'L011', number: 11, chapter: 2, difficulty: 'medium',
    optimalMoves: 13, optimalIsExact: true,
    tubes: ['YVBB', 'VYYV', 'BVRR', 'GRGG', 'RYGB', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-11' },
  }),
  // optimal=14 branching=10 deadEndRate=0.00 attempts=2
  defineLevel({
    id: 'L012', number: 12, chapter: 2, difficulty: 'medium',
    optimalMoves: 14, optimalIsExact: true,
    tubes: ['YVGB', 'VGBY', 'BGGV', 'YRRB', 'RRVY', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-12' },
  }),
  // optimal=14 branching=10 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L013', number: 13, chapter: 2, difficulty: 'medium',
    optimalMoves: 14, optimalIsExact: true,
    tubes: ['RRGR', 'RVBY', 'GYYG', 'YGBV', 'VBBV', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-13' },
  }),
  // optimal=15 branching=10 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L014', number: 14, chapter: 2, difficulty: 'medium',
    optimalMoves: 15, optimalIsExact: true,
    tubes: ['GVGB', 'YRRG', 'BVYR', 'RVVB', 'YGBY', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-14' },
  }),
  // optimal=16 branching=10 deadEndRate=0.00 attempts=4
  defineLevel({
    id: 'L015', number: 15, chapter: 2, difficulty: 'medium',
    optimalMoves: 16, optimalIsExact: true,
    tubes: ['GGVY', 'VBVR', 'RYRB', 'VGYR', 'BYBG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-15' },
  }),
  // optimal=17 branching=12 deadEndRate=0.03 attempts=6
  defineLevel({
    id: 'L016', number: 16, chapter: 2, difficulty: 'hard',
    optimalMoves: 17, optimalIsExact: true,
    tubes: ['BGYB', 'VGVV', 'RRRO', 'GORY', 'YVGO', 'BOBY', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-16' },
  }),
  // optimal=17 branching=12 deadEndRate=0.00 attempts=1
  defineLevel({
    id: 'L017', number: 17, chapter: 2, difficulty: 'hard',
    optimalMoves: 17, optimalIsExact: true,
    tubes: ['RYGG', 'BVVY', 'VYRO', 'VGRO', 'GOBB', 'BOYR', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-17' },
  }),
  // optimal=18 branching=12 deadEndRate=0.07 attempts=1
  defineLevel({
    id: 'L018', number: 18, chapter: 2, difficulty: 'hard',
    optimalMoves: 18, optimalIsExact: true,
    tubes: ['GRBO', 'OOGV', 'YBBR', 'RVYV', 'GBVY', 'OGRY', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-18' },
  }),
  // optimal=19 branching=12 deadEndRate=0.00 attempts=5
  defineLevel({
    id: 'L019', number: 19, chapter: 2, difficulty: 'hard',
    optimalMoves: 19, optimalIsExact: true,
    tubes: ['VGBB', 'YROV', 'OVRR', 'OYGY', 'RGBY', 'VOBG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-19' },
  }),
  // optimal=20 branching=12 deadEndRate=0.07 attempts=26
  defineLevel({
    id: 'L020', number: 20, chapter: 2, difficulty: 'hard',
    optimalMoves: 20, optimalIsExact: true,
    tubes: ['VBYG', 'RVGV', 'BROV', 'GBOY', 'RBOY', 'RYGO', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-20' },
  }),
  // optimal=21 branching=14 deadEndRate=0.16 attempts=1
  defineLevel({
    id: 'L021', number: 21, chapter: 2, difficulty: 'hard',
    optimalMoves: 21, optimalIsExact: true,
    tubes: ['YRVO', 'GOGR', 'GYCB', 'CCVB', 'ORRY', 'VBVY', 'BOCG', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-21' },
  }),
  // optimal=22 branching=14 deadEndRate=0.12 attempts=5
  defineLevel({
    id: 'L022', number: 22, chapter: 2, difficulty: 'hard',
    optimalMoves: 22, optimalIsExact: true,
    tubes: ['GRRC', 'VBCC', 'YVGO', 'YOCR', 'GBOG', 'YBVR', 'OYBV', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-22' },
  }),
  // optimal=23 branching=14 deadEndRate=0.14 attempts=2
  defineLevel({
    id: 'L023', number: 23, chapter: 2, difficulty: 'hard',
    optimalMoves: 23, optimalIsExact: true,
    tubes: ['OYVO', 'GOBO', 'BRRY', 'BGVC', 'RYVC', 'CGRG', 'CBYV', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-23' },
  }),
  // optimal=23 branching=14 deadEndRate=0.03 attempts=6
  defineLevel({
    id: 'L024', number: 24, chapter: 2, difficulty: 'expert',
    optimalMoves: 23, optimalIsExact: true,
    tubes: ['COCR', 'CGBY', 'BVBG', 'YRYV', 'GOVO', 'CYOB', 'VRGR', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-24' },
  }),
  // optimal=24 branching=14 deadEndRate=0.13 attempts=27
  defineLevel({
    id: 'L025', number: 25, chapter: 2, difficulty: 'expert',
    optimalMoves: 24, optimalIsExact: true,
    tubes: ['OYRO', 'BCYG', 'RVOB', 'RYVB', 'RGVG', 'CGCY', 'OBVC', '', ''],
    meta: { generatorVersion: 'g1', seed: 'level-25' },
  }),
];
