// GENERATED by scripts/generate-levels.ts (generator g1). Do not edit by hand.
// Chapter 6 (section 11.6): colour mixing. Every level is unsolvable without mixing.
import { defineLevel } from '../game/levelCodec';
import type { Level } from '../game/types';

export const MIXING_LEVELS: Level[] = [
  // optimal=9 (2 mixing pours) attempts=10
  defineLevel({
    id: 'L056', number: 56, chapter: 6, difficulty: 'hard',
    optimalMoves: 9, optimalIsExact: true,
    tutorial: 'mixing',
    tubes: [
      "BCMM",
      "CMBR",
      "RMCC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-56' },
  }),
  // optimal=11 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L057', number: 57, chapter: 6, difficulty: 'hard',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      "CGMM",
      "GMBR",
      "CBCC",
      "GGRM",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-57' },
  }),
  // optimal=12 (3 mixing pours) attempts=2
  defineLevel({
    id: 'L058', number: 58, chapter: 6, difficulty: 'hard',
    optimalMoves: 12, optimalIsExact: true,
    tubes: [
      "CVRC",
      "BMMC",
      "VCBR",
      "RMBM",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-58' },
  }),
  // optimal=11 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L059', number: 59, chapter: 6, difficulty: 'hard',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      "RCBR",
      "BYCB",
      "CYBC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-59' },
  }),
  // optimal=13 (4 mixing pours) attempts=3
  defineLevel({
    id: 'L060', number: 60, chapter: 6, difficulty: 'hard',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "CYCY",
      "BYOO",
      "RCOR",
      "YCBO",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"yellow","result":"orange"},{"a":"blue","b":"yellow","result":"green"}]},"reactor":{"moveLimit":17,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-60' },
  }),
  // optimal=15 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L061', number: 61, chapter: 6, difficulty: 'hard',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      "CBRB",
      "OMGM",
      "CCCB",
      "YMRG",
      "OMYR",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-61' },
  }),
  // optimal=17 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L062', number: 62, chapter: 6, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "OYGM",
      "BOCM",
      "M?B?C?C",
      "B?G?Y?R",
      "C?R?R?M",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-62' },
  }),
  // optimal=13 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L063', number: 63, chapter: 6, difficulty: 'expert',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "RCMC",
      "MBRC",
      "CMMR",
      "YBRY",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-63' },
  }),
  // optimal=14 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L064', number: 64, chapter: 6, difficulty: 'expert',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "R?G?G?R",
      "G?G?C?M",
      "C?B?M?M",
      "M?B?C?C",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-64' },
  }),
  // optimal=16 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L065', number: 65, chapter: 6, difficulty: 'expert',
    optimalMoves: 16, optimalIsExact: true,
    tubes: [
      "OCMR",
      "BYMM",
      "GMRG",
      "RCBY",
      "OCCB",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-65' },
  }),
];
