// GENERATED by scripts/generate-levels.ts (generator g1). Do not edit by hand.
// Chapters 6-8 (section 11.6): colour mixing, alone and with the other mechanics. Every level is unsolvable without mixing.
import { defineLevel } from '../game/levelCodec';
import type { Level } from '../game/types';

export const MIXING_LEVELS: Level[] = [
  // optimal=9 (2 mixing pours) attempts=10
  defineLevel({
    id: 'L056', number: 56, chapter: 6, difficulty: 'hard',
    optimalMoves: 9, optimalIsExact: true,
    tutorial: 'mixing',
    tubes: [
      "BCMM",
      "CMBR",
      "RMCC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-56' },
  }),
  // optimal=11 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L057', number: 57, chapter: 6, difficulty: 'hard',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      "CGMM",
      "GMBR",
      "CBCC",
      "GGRM",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-57' },
  }),
  // optimal=12 (3 mixing pours) attempts=2
  defineLevel({
    id: 'L058', number: 58, chapter: 6, difficulty: 'hard',
    optimalMoves: 12, optimalIsExact: true,
    tubes: [
      "CVRC",
      "BMMC",
      "VCBR",
      "RMBM",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-58' },
  }),
  // optimal=11 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L059', number: 59, chapter: 6, difficulty: 'hard',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      "RCBR",
      "BYCB",
      "CYBC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-59' },
  }),
  // optimal=13 (4 mixing pours) attempts=3
  defineLevel({
    id: 'L060', number: 60, chapter: 6, difficulty: 'hard',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "CYCY",
      "BYOO",
      "RCOR",
      "YCBO",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"yellow","result":"orange"},{"a":"blue","b":"yellow","result":"green"}]},"reactor":{"moveLimit":17,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-60' },
  }),
  // optimal=15 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L061', number: 61, chapter: 6, difficulty: 'hard',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      "CBRB",
      "OMGM",
      "CCCB",
      "YMRG",
      "OMYR",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-61' },
  }),
  // optimal=17 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L062', number: 62, chapter: 6, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "OYGM",
      "BOCM",
      "M?B?C?C",
      "B?G?Y?R",
      "C?R?R?M",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-62' },
  }),
  // optimal=13 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L063', number: 63, chapter: 6, difficulty: 'expert',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "RCMC",
      "MBRC",
      "CMMR",
      "YBRY",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-63' },
  }),
  // optimal=14 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L064', number: 64, chapter: 6, difficulty: 'expert',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "R?G?G?R",
      "G?G?C?M",
      "C?B?M?M",
      "M?B?C?C",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-64' },
  }),
  // optimal=16 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L065', number: 65, chapter: 6, difficulty: 'expert',
    optimalMoves: 16, optimalIsExact: true,
    tubes: [
      "OCMR",
      "BYMM",
      "GMRG",
      "RCBY",
      "OCCB",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-65' },
  }),
  // optimal=10 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L066', number: 66, chapter: 7, difficulty: 'expert',
    optimalMoves: 10, optimalIsExact: true,
    tubes: [
      "RCCB",
      "BBRC",
      {"liquids":"C^Y^BY","thawWhen":{"type":"tubesCompleted","count":1}},
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-66' },
  }),
  // optimal=13 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L067', number: 67, chapter: 7, difficulty: 'expert',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "CBMG",
      "MCCR",
      "RGCB",
      {"liquids":"M^GMG","thawWhen":{"type":"movesMade","count":6}},
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-67' },
  }),
  // optimal=12 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L068', number: 68, chapter: 7, difficulty: 'expert',
    optimalMoves: 12, optimalIsExact: true,
    tubes: [
      "YYRC",
      "BOOC",
      "BCOY",
      {"liquids":"OYRC","catalyst":{"triggerColor":"orange","effect":{"type":"unlockTube","tubeId":"T6"}}},
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"yellow","result":"orange"},{"a":"blue","b":"yellow","result":"green"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-68' },
  }),
  // optimal=13 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L069', number: 69, chapter: 7, difficulty: 'expert',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      "RCYC",
      {"liquids":"CRRM","catalyst":{"triggerColor":"yellow","effect":{"type":"unlockTube","tubeId":"T6"}}},
      "BBMC",
      "MMRY",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-69' },
  }),
  // optimal=18 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L070', number: 70, chapter: 7, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "BCMR",
      {"liquids":"M^OCG","thawWhen":{"type":"movesMade","count":7}},
      "YRBC",
      "MBYM",
      "GOCR",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]},"reactor":{"moveLimit":22,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-70' },
  }),
  // optimal=15 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L071', number: 71, chapter: 7, difficulty: 'expert',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      {"liquids":"MRMC","catalyst":{"triggerColor":"orange","effect":{"type":"thawTube","tubeId":"T2"}}},
      {"liquids":"Y^M^BC","thawWhen":{"type":"movesMade","count":40}},
      "MBYR",
      "CRRC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-71' },
  }),
  // optimal=14 (2 mixing pours) attempts=20
  defineLevel({
    id: 'L072', number: 72, chapter: 7, difficulty: 'expert',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      {"liquids":"RGCR","catalyst":{"triggerColor":"blue","effect":{"type":"revealTube","tubeId":"T4"}}},
      "G?G?B?B",
      "C?M?M?C",
      "M?M?C?G",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-72' },
  }),
  // optimal=17 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L073', number: 73, chapter: 7, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "R?M?Y?C",
      "B?G?C?R",
      "O?M?R?M",
      "O?C?B?B",
      "C?M?Y?G",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-73' },
  }),
  // optimal=18 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L074', number: 74, chapter: 7, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "BMGO",
      "B?M?R?B",
      "O?C?M?C",
      "Y?G?R?R",
      "MCYC",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-74' },
  }),
  // optimal=18 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L075', number: 75, chapter: 7, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "G?R?B?M",
      "CYGO",
      "CBRC",
      {"liquids":"B^YOR","thawWhen":{"type":"tubesCompleted","count":2}},
      "M?C?M?M",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-75' },
  }),
  // optimal=14 (2 mixing pours) attempts=1
  defineLevel({
    id: 'L076', number: 76, chapter: 8, difficulty: 'expert',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "M?Y?B?B",
      "C?R?C?Y",
      {"liquids":"M^C?C?M","thawWhen":{"type":"movesMade","count":5}},
      "R?R?R?M",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-76' },
  }),
  // optimal=18 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L077', number: 77, chapter: 8, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "CMBC",
      {"liquids":"M^OCB","thawWhen":{"type":"tubesCompleted","count":2}},
      "RMOR",
      {"liquids":"M^GYC","thawWhen":{"type":"tubesCompleted","count":2}},
      "YBRG",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-77' },
  }),
  // optimal=18 (4 mixing pours) attempts=6
  defineLevel({
    id: 'L078', number: 78, chapter: 8, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "YOCM",
      {"liquids":"B^R^GB","thawWhen":{"type":"tubesCompleted","count":1}},
      {"liquids":"M^C^CM","thawWhen":{"type":"tubesCompleted","count":2}},
      "BGRR",
      "MYOC",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-78' },
  }),
  // optimal=17 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L079', number: 79, chapter: 8, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "C?C?R?R",
      "O?M?B?M",
      "C?Y?R?B",
      "B?O?G?G",
      "M?M?C?Y",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-79' },
  }),
  // optimal=17 (4 mixing pours) attempts=1
  defineLevel({
    id: 'L080', number: 80, chapter: 8, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "CCGY",
      "BOMO",
      "Y?R?B?R",
      "M?B?G?C",
      "MCRM",
      {"liquids":"","catalyst":{"triggerColor":"cyan","effect":{"type":"unlockTube","tubeId":"T7"}}},
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]},"reactor":{"moveLimit":21,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-80' },
  }),
  // optimal=17 (4 mixing pours) attempts=7
  defineLevel({
    id: 'L081', number: 81, chapter: 8, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "B?Y?M?C",
      "Y?C?M?C",
      "R?B?G?C",
      {"liquids":"M?R?R?O","catalyst":{"triggerColor":"blue","effect":{"type":"revealTube","tubeId":"T1"}}},
      "G?O?M?B",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-81' },
  }),
  // optimal=18 (4 mixing pours) attempts=4
  defineLevel({
    id: 'L082', number: 82, chapter: 8, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      {"liquids":"M^B?R?Y","thawWhen":{"type":"movesMade","count":6}},
      "B?G?R?C",
      "M?O?Y?O",
      "M?C?R?M",
      "C?G?B?C",
      "",
      "",
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-82' },
  }),
  // optimal=19 (4 mixing pours) attempts=2
  defineLevel({
    id: 'L083', number: 83, chapter: 8, difficulty: 'expert',
    optimalMoves: 19, optimalIsExact: true,
    tubes: [
      "G?O?B?C",
      "R?M?Y?C",
      "B?R?R?B",
      "C?M?M?O",
      {"liquids":"C^M?Y?G","thawWhen":{"type":"tubesCompleted","count":1}},
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-83' },
  }),
  // optimal=19 (4 mixing pours) attempts=27
  defineLevel({
    id: 'L084', number: 84, chapter: 8, difficulty: 'expert',
    optimalMoves: 19, optimalIsExact: true,
    tubes: [
      "R?C?R?M",
      {"liquids":"Y^O?O?R","thawWhen":{"type":"movesMade","count":3}},
      "M?C?C?B",
      "G?C?B?B",
      {"liquids":"M^Y?G?M","thawWhen":{"type":"movesMade","count":3}},
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-84' },
  }),
  // optimal=19 (4 mixing pours) attempts=5
  defineLevel({
    id: 'L085', number: 85, chapter: 8, difficulty: 'expert',
    optimalMoves: 19, optimalIsExact: true,
    tubes: [
      "Y?B?C?O",
      "CGMC",
      "B?M?M?G",
      {"liquids":"R^Y^RC","thawWhen":{"type":"tubesCompleted","count":2}},
      "O?B?M?R",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    rules: {"mixing":{"pairs":[{"a":"red","b":"blue","result":"purple"},{"a":"blue","b":"yellow","result":"green"},{"a":"red","b":"yellow","result":"orange"}]}},
    meta: { generatorVersion: 'g1', seed: 'level-85' },
  }),
];
