// GENERATED by scripts/generate-levels.ts (generator g1). Do not edit by hand.
// Chapters 3-5 (section 11): frozen liquid, mystery liquid, catalysts and locked tubes.
// Tube rows are bottom -> top; '^' marks a frozen layer and '?' a hidden one.
import { defineLevel } from '../game/levelCodec';
import type { Level } from '../game/types';

export const MECHANIC_LEVELS: Level[] = [
  // optimal=11 (same deal without the mechanic: 10) attempts=88
  defineLevel({
    id: 'L026', number: 26, chapter: 3, difficulty: 'hard',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      {"liquids":"Y^RBY","thawWhen":{"type":"movesMade","count":7}},
      "BYYR",
      "GGGB",
      "GRBR",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-26' },
  }),
  // optimal=12 (same deal without the mechanic: 11) attempts=28
  defineLevel({
    id: 'L027', number: 27, chapter: 3, difficulty: 'hard',
    optimalMoves: 12, optimalIsExact: true,
    tubes: [
      {"liquids":"G^B^BG","thawWhen":{"type":"movesMade","count":5}},
      "RYGB",
      "RYYR",
      "YGRB",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-27' },
  }),
  // optimal=13 (same deal without the mechanic: 12) attempts=4
  defineLevel({
    id: 'L028', number: 28, chapter: 3, difficulty: 'hard',
    optimalMoves: 13, optimalIsExact: true,
    tubes: [
      {"liquids":"B^GRY","thawWhen":{"type":"tubesCompleted","count":2}},
      "RBRB",
      "GRGY",
      {"liquids":"B^GYY","thawWhen":{"type":"tubesCompleted","count":2}},
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-28' },
  }),
  // optimal=15 (same deal without the mechanic: 14) attempts=1
  defineLevel({
    id: 'L029', number: 29, chapter: 3, difficulty: 'hard',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      "VVGB",
      "VBYB",
      {"liquids":"Y^G^BR","thawWhen":{"type":"tubesCompleted","count":2}},
      "GGYR",
      "VRRY",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-29' },
  }),
  // optimal=14 (same deal without the mechanic: 13) attempts=12
  defineLevel({
    id: 'L030', number: 30, chapter: 3, difficulty: 'hard',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      {"liquids":"G^BBY","thawWhen":{"type":"movesMade","count":6}},
      {"liquids":"Y^VGB","thawWhen":{"type":"movesMade","count":7}},
      "RYVY",
      "RRRV",
      "BGGV",
      "",
      "",
    ],
    rules: {"reactor":{"moveLimit":18,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-30' },
  }),
  // optimal=17 (same deal without the mechanic: 16) attempts=3
  defineLevel({
    id: 'L031', number: 31, chapter: 3, difficulty: 'hard',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "VGYG",
      "RVBG",
      "RGBB",
      {"liquids":"Y^V^YB","thawWhen":{"type":"colorCompleted","color":"green"}},
      {"liquids":"R^V^YR","thawWhen":{"type":"colorCompleted","color":"yellow"}},
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-31' },
  }),
  // optimal=16 (same deal without the mechanic: 15) attempts=4
  defineLevel({
    id: 'L032', number: 32, chapter: 3, difficulty: 'hard',
    optimalMoves: 16, optimalIsExact: true,
    tubes: [
      {"liquids":"R^Y^YB","thawWhen":{"type":"tubesCompleted","count":1}},
      "RGGB",
      "RBYV",
      "GVRG",
      {"liquids":"B^V^YV","thawWhen":{"type":"tubesCompleted","count":1}},
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-32' },
  }),
  // optimal=17 (same deal without the mechanic: 16) attempts=4
  defineLevel({
    id: 'L033', number: 33, chapter: 3, difficulty: 'hard',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "RROB",
      "YVVY",
      "OBOY",
      "ROGY",
      "GGRB",
      {"liquids":"B^V^VG","thawWhen":{"type":"movesMade","count":7}},
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-33' },
  }),
  // optimal=20 (same deal without the mechanic: 19) attempts=22
  defineLevel({
    id: 'L034', number: 34, chapter: 3, difficulty: 'hard',
    optimalMoves: 20, optimalIsExact: true,
    tubes: [
      "OYGB",
      {"liquids":"Y^ROR","thawWhen":{"type":"tubesCompleted","count":1}},
      "RBRB",
      "OGYV",
      "YVOV",
      {"liquids":"B^GGV","thawWhen":{"type":"tubesCompleted","count":1}},
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-34' },
  }),
  // optimal=18 (same deal without the mechanic: 17) attempts=5
  defineLevel({
    id: 'L035', number: 35, chapter: 3, difficulty: 'hard',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "OBRY",
      {"liquids":"Y^Y^RV","thawWhen":{"type":"movesMade","count":6}},
      "VVBG",
      {"liquids":"G^O^BY","thawWhen":{"type":"movesMade","count":6}},
      "BGVO",
      "GROR",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-35' },
  }),
  // optimal=12 (same deal without the mechanic: 11) attempts=1
  defineLevel({
    id: 'L036', number: 36, chapter: 4, difficulty: 'hard',
    optimalMoves: 12, optimalIsExact: true,
    tubes: [
      "G?R?Y?B",
      "RRRB",
      "GYGB",
      "G?Y?Y?B",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-36' },
  }),
  // optimal=14 (same deal without the mechanic: 10) attempts=1
  defineLevel({
    id: 'L037', number: 37, chapter: 4, difficulty: 'hard',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "G?G?B?B",
      "B?Y?Y?B",
      "RYGR",
      "R?R?G?Y",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-37' },
  }),
  // optimal=14 (same deal without the mechanic: 10) attempts=1
  defineLevel({
    id: 'L038', number: 38, chapter: 4, difficulty: 'hard',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "G?G?G?B",
      "R?R?B?G",
      "R?Y?B?Y",
      "B?Y?Y?R",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-38' },
  }),
  // optimal=17 (same deal without the mechanic: 16) attempts=1
  defineLevel({
    id: 'L039', number: 39, chapter: 4, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "RBYV",
      "Y?B?R?V",
      "BGVG",
      "B?V?R?Y",
      "Y?G?G?R",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-39' },
  }),
  // optimal=17 (same deal without the mechanic: 14) attempts=1
  defineLevel({
    id: 'L040', number: 40, chapter: 4, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "V?B?V?V",
      "R?G?G?Y",
      "GYBB",
      "Y?Y?B?R",
      "R?G?V?R",
      "",
      "",
    ],
    rules: {"reactor":{"moveLimit":21,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-40' },
  }),
  // optimal=17 (same deal without the mechanic: 15) attempts=1
  defineLevel({
    id: 'L041', number: 41, chapter: 4, difficulty: 'expert',
    optimalMoves: 17, optimalIsExact: true,
    tubes: [
      "Y?Y?G?V",
      "B?R?V?G",
      "V?R?G?B",
      "Y?Y?B?R",
      "V?R?B?G",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-41' },
  }),
  // optimal=18 (same deal without the mechanic: 15) attempts=1
  defineLevel({
    id: 'L042', number: 42, chapter: 4, difficulty: 'expert',
    optimalMoves: 18, optimalIsExact: true,
    tubes: [
      "G?B?R?V",
      "OGVR",
      "RGVV",
      "Y?O?O?R",
      "B?B?Y?Y",
      "YBGO",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-42' },
  }),
  // optimal=19 (same deal without the mechanic: 18) attempts=1
  defineLevel({
    id: 'L043', number: 43, chapter: 4, difficulty: 'expert',
    optimalMoves: 19, optimalIsExact: true,
    tubes: [
      "R?V?B?Y",
      "G?O?B?B",
      "V?G?R?G",
      "BVOR",
      "OYYV",
      "O?R?Y?G",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-43' },
  }),
  // optimal=20 (same deal without the mechanic: 16) attempts=1
  defineLevel({
    id: 'L044', number: 44, chapter: 4, difficulty: 'expert',
    optimalMoves: 20, optimalIsExact: true,
    tubes: [
      "B?B?B?R",
      "G?Y?O?R",
      "G?B?R?Y",
      "O?V?O?G",
      "Y?Y?V?V",
      "G?O?R?V",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-44' },
  }),
  // optimal=21 (same deal without the mechanic: 17) attempts=3
  defineLevel({
    id: 'L045', number: 45, chapter: 4, difficulty: 'expert',
    optimalMoves: 21, optimalIsExact: true,
    tubes: [
      "R?O?V?R",
      "Y?O?B?R",
      "G?G?G?O",
      "V?V?Y?V",
      "B?R?Y?O",
      "B?Y?B?G",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-45' },
  }),
  // optimal=15 (same deal without the mechanic: 14) attempts=10
  defineLevel({
    id: 'L046', number: 46, chapter: 5, difficulty: 'expert',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      "GYGY",
      "BRGB",
      "RBYR",
      "BYGR",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":7}}},
    ],
    meta: { generatorVersion: 'g1', seed: 'level-46' },
  }),
  // optimal=11 (same deal without the mechanic: 11) attempts=4
  defineLevel({
    id: 'L047', number: 47, chapter: 5, difficulty: 'expert',
    optimalMoves: 11, optimalIsExact: true,
    tubes: [
      "BRBY",
      "YYBG",
      "GGBR",
      "YRRG",
      "",
      {"liquids":"","catalyst":{"triggerColor":"red","effect":{"type":"unlockTube","tubeId":"T7"}}},
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
    ],
    meta: { generatorVersion: 'g1', seed: 'level-47' },
  }),
  // optimal=14 (same deal without the mechanic: 13) attempts=2
  defineLevel({
    id: 'L048', number: 48, chapter: 5, difficulty: 'expert',
    optimalMoves: 14, optimalIsExact: true,
    tubes: [
      "YVGG",
      "RYRV",
      "RGGY",
      {"liquids":"VRBV","lock":{"unlockWhen":{"type":"tubesCompleted","count":1}}},
      "BBYB",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-48' },
  }),
  // optimal=16 (same deal without the mechanic: 16) attempts=1
  defineLevel({
    id: 'L049', number: 49, chapter: 5, difficulty: 'expert',
    optimalMoves: 16, optimalIsExact: true,
    tubes: [
      "GRGG",
      {"liquids":"Y^V^BV","thawWhen":{"type":"movesMade","count":40}},
      "BRYB",
      "VRYY",
      "VBRG",
      "",
      {"liquids":"","catalyst":{"triggerColor":"yellow","effect":{"type":"thawTube","tubeId":"T2"}}},
    ],
    meta: { generatorVersion: 'g1', seed: 'level-49' },
  }),
  // optimal=16 (same deal without the mechanic: 15) attempts=4
  defineLevel({
    id: 'L050', number: 50, chapter: 5, difficulty: 'expert',
    optimalMoves: 16, optimalIsExact: true,
    tubes: [
      "GVRV",
      "BYGY",
      {"liquids":"VRGR","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
      "GYBB",
      {"liquids":"YBVR","catalyst":{"triggerColor":"yellow","effect":{"type":"unlockTube","tubeId":"T3"}}},
      "",
      "",
    ],
    rules: {"reactor":{"moveLimit":20,"bonusCoins":50}},
    meta: { generatorVersion: 'g1', seed: 'level-50' },
  }),
  // optimal=15 (same deal without the mechanic: 15) attempts=1
  defineLevel({
    id: 'L051', number: 51, chapter: 5, difficulty: 'expert',
    optimalMoves: 15, optimalIsExact: true,
    tubes: [
      "VYYR",
      {"liquids":"BVBY","catalyst":{"triggerColor":"blue","effect":{"type":"revealTube","tubeId":"T4"}}},
      "G?R?G?B",
      "R?R?G?Y",
      "B?V?G?V",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-51' },
  }),
  // optimal=19 (same deal without the mechanic: 19) attempts=13
  defineLevel({
    id: 'L052', number: 52, chapter: 5, difficulty: 'expert',
    optimalMoves: 19, optimalIsExact: true,
    tubes: [
      "GOGB",
      "VYVB",
      "BRVO",
      {"liquids":"OVRR","catalyst":{"triggerColor":"purple","effect":{"type":"unlockTube","tubeId":"T9"}}},
      "GYOB",
      "YRGY",
      "",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":40}}},
    ],
    meta: { generatorVersion: 'g1', seed: 'level-52' },
  }),
  // optimal=21 (same deal without the mechanic: 20) attempts=1
  defineLevel({
    id: 'L053', number: 53, chapter: 5, difficulty: 'expert',
    optimalMoves: 21, optimalIsExact: true,
    tubes: [
      "ROYB",
      {"liquids":"RBGV","catalyst":{"triggerColor":"green","effect":{"type":"thawTube","tubeId":"T4"}}},
      "VGOB",
      {"liquids":"O^R^GY","thawWhen":{"type":"movesMade","count":40}},
      "YVBR",
      "VGOY",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-53' },
  }),
  // optimal=21 (same deal without the mechanic: 18) attempts=1
  defineLevel({
    id: 'L054', number: 54, chapter: 5, difficulty: 'expert',
    optimalMoves: 21, optimalIsExact: true,
    tubes: [
      "RBBG",
      {"liquids":"OVRV","lock":{"unlockWhen":{"type":"movesMade","count":5}}},
      "YRGR",
      "GYVY",
      "OGVO",
      "YOBB",
      "",
      {"liquids":"","lock":{"unlockWhen":{"type":"movesMade","count":4}}},
    ],
    meta: { generatorVersion: 'g1', seed: 'level-54' },
  }),
  // optimal=20 (same deal without the mechanic: 17) attempts=8
  defineLevel({
    id: 'L055', number: 55, chapter: 5, difficulty: 'expert',
    optimalMoves: 20, optimalIsExact: true,
    tubes: [
      "Y?B?V?R",
      "B?B?R?Y",
      "R?G?O?G",
      {"liquids":"V?G?O?G","catalyst":{"triggerColor":"purple","effect":{"type":"revealTube","tubeId":"T4"}}},
      "B?Y?Y?R",
      "O?V?V?O",
      "",
      "",
    ],
    meta: { generatorVersion: 'g1', seed: 'level-55' },
  }),
];
